version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hirehub-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - CHAT_ENCRYPTION_KEY=${CHAT_ENCRYPTION_KEY}
      - CHAPA_SECRET_KEY=${CHAPA_SECRET_KEY}
      - FRONTEND_URL=http://localhost:8081
      - BACKEND_URL=http://localhost:4000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/database.sqlite:/app/database.sqlite
    networks:
      - hirehub-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Job Seeker Portal (User Portal)
  job-seeker-portal:
    build:
      context: ./Frontend/USER(dagi)
      dockerfile: Dockerfile
    container_name: hirehub-job-seeker
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - hirehub-network
    restart: unless-stopped

  # Employer Portal
  employer-portal:
    build:
      context: ./Frontend/employer-connect-pro-main
      dockerfile: Dockerfile
    container_name: hirehub-employer
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hirehub-network
    restart: unless-stopped

  # Auth Hub
  auth-hub:
    build:
      context: ./Frontend/seekr-companion-main
      dockerfile: Dockerfile
    container_name: hirehub-auth
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - hirehub-network
    restart: unless-stopped

  # Admin Panel
  admin-panel:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: hirehub-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_AUTH_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_JOBS_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_ADMIN_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_PAYMENT_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_AUTH_HUB_URL=http://localhost:3002
      - NEXT_PUBLIC_TOKEN_STORAGE_KEY=hirehub_token
      - NEXT_PUBLIC_REFRESH_TOKEN_STORAGE_KEY=hirehub_refresh_token
    depends_on:
      - backend
    networks:
      - hirehub-network
    restart: unless-stopped

networks:
  hirehub-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-database:

